---
- name: Create user on a linux server
  hosts: localhost
  become: yes
  gather_facts: false
  vars:
    - user: vishal
    - password: Unix@2020
    - dir_name: testing
    - main_path: /Users/beginneracademy/Downloads/Desktop/beginner.academy/Docker_Ext/new/ansible

  tasks:
    - name: Creates directory
      file:
        path: "{{ main_path }}/{{ user }}/{{ dir_name }}"
        state: directory

    - name: copy src.txt as dest.txt in the same dir
      copy:
        src: /tmp/src.txt
        dest: "{{ main_path }}/{{ user }}/{{ dir_name }}/Dest.txt"